# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-11 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apistep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=100, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('apiurl', models.CharField(max_length=200, verbose_name='url\u5730\u5740')),
                (
                    'apiparamvalue',
                    models.CharField(max_length=800, verbose_name='\u8bf7\u6c42\u53c2\u6570\u548c\u503c')),
                ('apimethod', models.CharField(
                    choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'),
                             ('patch', 'patch')], default='get', max_length=200, null=True,
                    verbose_name='\u8bf7\u6c42\u65b9\u6cd5')),
                ('apiresult', models.CharField(max_length=200, verbose_name='\u9884\u671f\u7ed3\u679c')),
                ('apistatus', models.BooleanField(verbose_name='\u662f\u5426\u901a\u8fc7')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Apitest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apitestname', models.CharField(max_length=64, verbose_name='\u6d41\u7a0b\u63a5\u53e3\u540d\u79f0')),
                ('apitestdesc', models.CharField(max_length=64, null=True, verbose_name='\u63cf\u8ff0')),
                ('apitester', models.CharField(max_length=16, verbose_name='\u6d4b\u8bd5\u8d1f\u8d23\u4eba')),
                ('apitestresult', models.BooleanField(verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6d41\u7a0b\u573a\u666f\u63a5\u53e3',
                'verbose_name_plural': '\u6d41\u7a0b\u573a\u666f\u63a5\u53e3',
            },
        ),
        migrations.AddField(
            model_name='apistep',
            name='Apitest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.Apitest'),
        ),
    ]
