# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appcasename', models.CharField(max_length=200, verbose_name='\u7528\u4f8b\u540d\u79f0')),
                ('apptestresult', models.BooleanField(verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
                ('apptester', models.CharField(max_length=16, verbose_name='\u6d4b\u8bd5\u8d1f\u8d23\u4eba')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('Product',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'app\u6d4b\u8bd5\u7528\u4f8b',
                'verbose_name_plural': 'app\u6d4b\u8bd5\u7528\u4f8b',
            },
        ),
        migrations.CreateModel(
            name='Appcasestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appteststep', models.CharField(max_length=200, verbose_name='\u6d4b\u8bd5\u6b65\u9aa4')),
                ('apptestobjname',
                 models.CharField(max_length=200, verbose_name='\u6d4b\u8bd5\u5bf9\u8c61\u540d\u79f0\u63cf\u8ff0')),
                ('appfindmethod', models.CharField(max_length=200, verbose_name='\u64cd\u4f5c\u65b9\u6cd5')),
                ('appevelement', models.CharField(max_length=800, verbose_name='\u63a7\u4ef6\u5143\u7d20')),
                ('apptestdata', models.CharField(max_length=200, null=True, verbose_name='\u6d4b\u8bd5\u6570\u636e')),
                ('appassertdata', models.CharField(max_length=200, verbose_name='\u9a8c\u8bc1\u6570\u636e')),
                ('apptestresult', models.BooleanField(verbose_name='\u6d4b\u8bd5\u7ed3\u679c')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('Appcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptest.Appcase')),
            ],
        ),
    ]
